create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, bio text, github_username text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.projects(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,slug text not null,short_description text,full_description text,cover_url text,category text,status text not null default 'idea' check(status in('idea','planning','development','testing','deployed','completed','paused','archived')),priority text not null default 'medium' check(priority in('low','medium','high')),progress int not null default 0 check(progress between 0 and 100),github_url text,live_url text,docs_url text,api_url text,hosting_provider text,visibility text not null default 'private' check(visibility in('private','unlisted','public')),featured boolean not null default false,start_date date,target_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,slug));
create table if not exists public.tags(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,color text,unique(user_id,name));
create table if not exists public.project_tags(project_id uuid references public.projects(id) on delete cascade,tag_id uuid references public.tags(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,primary key(project_id,tag_id));
create table if not exists public.technologies(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,category text,unique(user_id,name));
create table if not exists public.project_technologies(project_id uuid references public.projects(id) on delete cascade,technology_id uuid references public.technologies(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,primary key(project_id,technology_id));
create table if not exists public.project_tasks(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,description text,status text not null default 'todo' check(status in('todo','doing','done')),priority text not null default 'medium' check(priority in('low','medium','high')),due_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.project_milestones(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,description text,due_date date,completed boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.project_updates(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,body text,version text,created_at timestamptz not null default now());
create table if not exists public.project_notes(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,content text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.project_links(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,label text not null,url text not null,kind text default 'other',created_at timestamptz not null default now());
create table if not exists public.project_files(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,name text not null,path text not null,mime_type text,size_bytes bigint,created_at timestamptz not null default now());
create table if not exists public.activity_logs(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,project_id uuid references public.projects(id) on delete cascade,action text not null,details jsonb default '{}'::jsonb,created_at timestamptz not null default now());
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
do $$begin if not exists(select 1 from pg_trigger where tgname='projects_touch') then create trigger projects_touch before update on public.projects for each row execute function public.touch_updated_at(); end if; end$$;
do $$begin if not exists(select 1 from pg_trigger where tgname='tasks_touch') then create trigger tasks_touch before update on public.project_tasks for each row execute function public.touch_updated_at(); end if; end$$;
do $$begin if not exists(select 1 from pg_trigger where tgname='notes_touch') then create trigger notes_touch before update on public.project_notes for each row execute function public.touch_updated_at(); end if; end$$;

alter table public.profiles enable row level security; alter table public.projects enable row level security; alter table public.tags enable row level security; alter table public.project_tags enable row level security; alter table public.technologies enable row level security; alter table public.project_technologies enable row level security; alter table public.project_tasks enable row level security; alter table public.project_milestones enable row level security; alter table public.project_updates enable row level security; alter table public.project_notes enable row level security; alter table public.project_links enable row level security; alter table public.project_files enable row level security; alter table public.activity_logs enable row level security;

do $$ declare t text; begin foreach t in array array['projects','tags','project_tags','technologies','project_technologies','project_tasks','project_milestones','project_updates','project_notes','project_links','project_files','activity_logs'] loop execute format('drop policy if exists %I on public.%I','own_all_'||t,t); execute format('create policy %I on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)','own_all_'||t,t); end loop; end $$;
-- profiles uses id rather than user_id
drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
-- public projects may be read without authentication
create policy projects_public_read on public.projects for select using(visibility='public');

insert into storage.buckets(id,name,public) values('project-files','project-files',false) on conflict(id) do nothing;
drop policy if exists "project_files_storage_select" on storage.objects;
drop policy if exists "project_files_storage_insert" on storage.objects;
drop policy if exists "project_files_storage_update" on storage.objects;
drop policy if exists "project_files_storage_delete" on storage.objects;
create policy "project_files_storage_select" on storage.objects for select using(bucket_id='project-files' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "project_files_storage_insert" on storage.objects for insert with check(bucket_id='project-files' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "project_files_storage_update" on storage.objects for update using(bucket_id='project-files' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "project_files_storage_delete" on storage.objects for delete using(bucket_id='project-files' and auth.uid()::text=(storage.foldername(name))[1]);

create index if not exists projects_user_updated_idx on public.projects(user_id,updated_at desc); create index if not exists tasks_user_status_idx on public.project_tasks(user_id,status); create index if not exists updates_project_idx on public.project_updates(project_id,created_at desc); create index if not exists activity_user_created_idx on public.activity_logs(user_id,created_at desc);
